### ISSUE TITLE
Cannot get the log view of the topic end of module 01

### ISSUE THREAD

**Issue by emmanuelbernard** [debezium/microservices-lab#39]
> We can check that describing the topic one more time.

`oc exec -it my-cluster-kafka-0 -- bin/kafka-topics.sh --zookeeper localhost:2181 --describe`

does not return what is shown in the lab.

I get

```
[build@localhost strimzi-0.8.0]$ oc exec -it my-cluster-kafka-0 -- bin/kafka-topics.sh --zookeeper localhost:2181 --describe
Defaulting container name to kafka.
Use 'oc describe pod/my-cluster-kafka-0 -n voxxed' to see all of the containers in this pod.
```

Also the GitHub rendering is confusing and I did nto know I had to stop at the end of --describe. I ended up selecting the line below too

**Comment by emmanuelbernard** [comment]
Likewise

```
oc exec -it my-cluster-kafka-0 -- bin/kafka-topics.sh --zookeeper localhost:2181 --list
```
does not return what is expected.

```
[build@localhost strimzi-0.8.0]$ oc exec -it my-cluster-kafka-0 -- bin/kafka-topics.sh --zookeeper localhost:2181 --list
Defaulting container name to kafka.
Use 'oc describe pod/my-cluster-kafka-0 -n voxxed' to see all of the containers in this pod.
```

**Comment by jpechane** [comment]
Fixed in https://github.com/debezium/microservices-lab/pull/51

**Comment by gunnarmorling** [comment]
I'm still seeing this issue with one broker node.

Perhaps @ppatierno or @scholzj have an idea:

I'm getting this when running `oc describe kafkatopic my-topic`:

Events:
  Type     Reason  Age        From                                     Message
  ----     ------  ----       ----                                     -------
  Warning          <unknown>  io.strimzi.operator.topic.TopicOperator  Failure processing KafkaTopic watch event ADDED on resource my-topic with labels {strimzi.io/cluster=my-cluster}: KeeperErrorCode = Session expired for for path: /strimzi/topics/my-topic

**Comment by gunnarmorling** [comment]
Ok, so the issue is that the topic operator looses the connection to the ZK node when it gets restarted as part of the limit configuration. It's a known issue in Strimzi and should be fixed soon. I've filed https://github.com/debezium/microservices-lab/pull/58 for working around it.

**Comment by gunnarmorling** [comment]
Done.
